CREATE TABLE INVOICES(CUSTOMER_ID CHAR(10), VALUE INTEGER);

CREATE TABLE CUSTOMERS(NAME CHAR(15), ID CHAR(10), foreign key (ID) references
	INVOICES(CUSTOMER_ID));
    
INSERT INTO INVOICES VALUES("Julia", 1908934532);   
INSERT INTO INVOICES VALUES("Samantha", 3131313131);   
INSERT INTO INVOICES VALUES("John", 5678236461);   
INSERT INTO INVOICES VALUES("Chris", 8013472345);
INSERT INTO INVOICES VALUES("Thalia", 05082020);  

INSERT INTO INVOICES VALUES("name1", "Julia");
INSERT INTO INVOICES VALUES("name2", "Samantha");
INSERT INTO INVOICES VALUES("name3", "John");
INSERT INTO INVOICES VALUES("name4", "Chris");
INSERT INTO INVOICES VALUES("name5", "Thalia");
INSERT INTO INVOICES VALUES("name6", "Olivia");


SELECT * FROM INVOICES;
SELECT * FROM CUSOMTERS;

SELECT c.NAME from CUSTOMERS c,INVOICES i where c.ID = i.CUSTOMER_ID and i.VALUE in (SELECT max(VALUE) FROM INVOICES);